### ISSUE TITLE
Avoid tweets without questions at Timeline

### ISSUE THREAD

**Issue by santosant** [sibelius/ccsseraphini#114]
# Question

We can avoid this kind of tweet at Timeline??

![image](https://user-images.githubusercontent.com/17819811/151422032-5d508930-9b8d-4ad5-9b43-cb70d9fa044d.png)

**Comment by biantris** [comment]
Actually he did, but the cc is in the reply, I think it's ok to show

![image](https://user-images.githubusercontent.com/65451957/151424279-b1ae6dcf-1e5e-4f69-8539-0a0074291a35.png)
