### ISSUE TITLE
Error when clicking Phantom donate button

### ISSUE THREAD

**Issue by Lorenzobattistela** [sibelius/ccsseraphini#115]
# Bug

Testing the official website, I tried to click the Phantom donate button:
![image](https://user-images.githubusercontent.com/70359945/151434815-006a699c-51a3-4eb1-8d3d-331469199be1.png)
When clicked the button returned me an error:
![image](https://user-images.githubusercontent.com/70359945/151434765-f34a5d28-85e1-4018-8382-061a70d3655c.png)

The cause of the error is probably a MetaMask or wallet connection problem (as I tested with no wallet connected), but **no log or description was provided in the error, just empty keys {}**. I tried with my MetaMask wallet connected and the same error was returned. Since there was no error description, this bug can be user caused or code caused.

## Environment info
Not needed, found in the official website
https://sseraphini.cc/

## Steps To Reproduce

Clicked the button showed above (donate crypto with Sol)

Describe what you expected to happen:

1. Open some tab or pop-up to complete the donation

2. Confirm the donation and transfer the value

## Reproducible sample code
Bug found in the website

**Comment by Lorenzobattistela** [comment]
I suggest investigating the code, i would do it myself but im not familiar with the stack used

**Comment by sibelius** [comment]
fixed on main branch

can you test again?

reopen if needed

**Comment by Lorenzobattistela** [comment]
> fixed on main branch
> 
> 
> 
> can you test again?
> 
> 
> 
> reopen if needed

Testes again, now the error returns me the reason:

Check if Phantom is installed
