### ISSUE TITLE
Should we migrate to the koo?

### ISSUE THREAD

**Issue by tgmarinho** [sibelius/ccsseraphini#1207]
Now that Twitter is dying, should we migrate the data to the koo and post new memes in the koo as well?

**Comment by ViniBGoulart** [comment]
https://help.twitter.com/en/managing-your-account/accessing-your-twitter-data

**Comment by sibelius** [comment]
both

**Comment by jeffque** [comment]
- [ ] Koo api to create a post with media (sseramemes)
- [ ] Koo api to listen mentions (cc sseraphini and sseramemes)
- [ ] Koo api to retweet (cc sseraphini and sseramemes)

**Comment by jeffque** [comment]
Excerpt from Koo team:

> API is not available in your country. In future once it is available, we will keep you notified.Until then, we appreciate your patience and understanding 

So, for now they don't have a way to integrate =/

**Comment by sibelius** [comment]
let's close for now
