### ISSUE TITLE
donation

### ISSUE THREAD

**Issue by sibelius** [sibelius/ccsseraphini#13]
- [x] be able to donate btc/eth to my wallet

**Comment by sibelius** [comment]
- [ ] ethereum
- [ ] bitcoin
- [ ] solana

**Comment by sibelius** [comment]
![image](https://user-images.githubusercontent.com/2005841/149517452-c6b5a4b1-374c-424a-bbc7-5479ac3dc737.png)

**Comment by sibelius** [comment]
eth - 0xb9A5d5BA75339B1fF4cCdAefa0e3da1543A65d52

**Comment by daniloab** [comment]
related https://github.com/sibelius/ccsseraphini/issues/15

**Comment by sibelius** [comment]
- [  ] sol 24gVn4dinDmqHeCmXHhySet3swxMc3Jup7iYSFTbgztm

**Comment by sibelius** [comment]
maybe too hard to btc
