### ISSUE TITLE
tweet render link preview

### ISSUE THREAD

**Issue by sibelius** [sibelius/ccsseraphini#136]

**Comment by ubmit** [comment]
I wasn't able to understand what we should achieve by solving this issue. Do you mind giving an example or describing it further?

**Comment by sibelius** [comment]
Check this tweet https://twitter.com/sseraphini/status/1488482763548332041?s=21

On twitter 
And also on sseraphini.cc

**Comment by ubmit** [comment]
Got it! I'll start working on this 🙌

**Comment by ubmit** [comment]
Is the `main` branch outdated (when comparing to production) somehow? When running it locally, there isn't the "latest tweets" section.

![image](https://user-images.githubusercontent.com/8797405/152037413-c0dda96e-7807-469b-a896-63a194ca9388.png)

**Comment by sibelius** [comment]
you need a twitter bearer token https://github.com/sibelius/ccsseraphini/tree/main/apps/web#twitter_bearer_token

**Comment by sibelius** [comment]
maybe we can have an error if twitter bearer token is missing on dev mode

**Comment by ubmit** [comment]
Sorry, didn't realize that there was a `README` inside the `web` folder 😓. Thanks 🙌

**Comment by ubmit** [comment]
Solved by #143
