### ISSUE TITLE
add a modal

### ISSUE THREAD

**Issue by EmanuelCampos** [sibelius/ccsseraphini#15]
- [ ] open a modal when click on the photo of sseraphini
- [ ] add ETH/BTC sseraphini wallets to receive donations
- [ ] add the sseraphini's patreon URL

**Comment by ftonato** [comment]
![over](https://user-images.githubusercontent.com/5417662/149846212-171205fb-f9c7-429a-9d1e-3d8154697b25.gif)

**Comment by daniloab** [comment]
related https://github.com/sibelius/ccsseraphini/issues/13
