### ISSUE TITLE
The site can’t be reached

### ISSUE THREAD

**Issue by JorgeDorio** [sibelius/ccsseraphini#1524]
# Bug

I tried to access the `https://sseraphini.cc/` website through many browsers and devices, but none of them worked

## Steps To Reproduce

Open any browser and access the website https://sseraphini.cc/

Describe what you expected to happen:

1. Render [this page](https://cdn.discordapp.com/attachments/1065780489329328138/1065781054344003584/image.png)

**Comment by tgmarinho** [comment]
it's working

**Comment by italosantana** [comment]
@JorgeDorio @tgmarinho domain expired since the end of January.

**Comment by italosantana** [comment]
@JorgeDorio @tgmarinho domain expired since the end of January.
