### ISSUE TITLE
latest cc @sseraphini tweets

### ISSUE THREAD

**Issue by sibelius** [sibelius/ccsseraphini#20]
- [  ] a twitter timeline with all tweets that has `cc @sseraphini`

**Comment by danielcti** [comment]
I can work on it. Should we add the tweet API logic in the api folder, right?

**Comment by danielcti** [comment]
@sibelius I've created a Twitter API account, but I think you will have your own API account, right? I will get the Bearer Token from the .env file, so you can put your token there.
Btw I will open the PR soon.

**Comment by sibelius** [comment]
Keep the env name in a .env.example and I add a secret later on

**Comment by danielcti** [comment]
TODO:
- [ ] Add a button in the homepage redirecting to this page
- [ ] Fetch more than 10 tweets, with pagination or infinite scroll.
- [ ] Add how long ago the tweet was added, i.e., (12min ago).

**Comment by sibelius** [comment]
I'm gonna split new features in more issues, so more people can contribute
