### ISSUE TITLE
Update sseramemes Twitter API

### ISSUE THREAD

**Issue by arantespp** [sibelius/ccsseraphini#2148]
# Bug

We need to migrate sseramemes Twitter API from v1 to v2.

[tweetMeme.ts](https://github.com/sibelius/ccsseraphini/blob/main/apps/sseramemes/src/tweetMeme.ts) uses API v1 and this version doesn't work anymore. We need to remove all `client.v1`

![image](https://github.com/sibelius/ccsseraphini/assets/16626980/0e276b30-3687-4c51-afb7-2f4c11c4f19b)

**Comment by igorfelipeduca** [comment]
the twitter api v2 function is to manage tweets and update its metadata or content tagging

as you can see in the api v2, their fundamentals are about managing existent tweets and its content filters, rates, etc.*

https://developer.twitter.com/en/docs/twitter-api/data-dictionary/introduction

so, updating to the api v2 would not solve this issue
