### ISSUE TITLE
distributed RT proposal

### ISSUE THREAD

**Issue by sibelius** [sibelius/ccsseraphini#224]
I have being tagged more than 30k times this month

![image](https://user-images.githubusercontent.com/2005841/155717399-ae14489b-3189-42f6-8c52-3795086c562c.png)

- [ ] be able to select a group of twitter users to be able to RT like me
- [ ] sseraphini.cc will grant access to these users, and only enable them to RT 'cc @sseraphini' tweets
- [ ] it should not be possible to post like me, or see or write DMs

**Comment by NicolasPereira** [comment]
I believe it is too dangerous, especially the SPAM issue!

Is there a filter for RT's today or is it automated?

if it's automated and doesn't have a filter, someone could take advantage of it and share not-so-nice things

**Comment by sibelius** [comment]
manual

**Comment by pjonatansr** [comment]
how about if the community vote to validate the content?

And only when the post achieve a proposed number of validations a bot can rt/like

I think If it is your validation, only one is enough for rt/like

**Comment by sibelius** [comment]
We can do a voting mechanism, but it would be slow

We can try many solutions

**Comment by tgmarinho** [comment]
to automate RT you need blacklist words, and RT words that matter for the purpose of the ccsseraphine, 
you'll not RT "java is shit", "react is dead", but you can RT "how to create a CRUD with java", "how to manage state with react"
white/preferred word are: "java", "react", and others and others.
This feature require a backend (db) to store data and streams from twitter to read and RT 
even a tweet with preferred word and blacklisted word you can't RT

**Comment by arantespp** [comment]
We can discuss here https://github.com/sibelius/ccsseraphini/issues/576
