### ISSUE TITLE
Bot that flood your server #ccseraphine channel with new tweets

### ISSUE THREAD

**Issue by tgmarinho** [sibelius/ccsseraphini#226]
Bot that flood your server #ccseraphine channel with new tweets

_Originally posted by @tgmarinho in https://github.com/sibelius/ccsseraphini/issues/157#issuecomment-1050135893_

**Comment by tgmarinho** [comment]
https://github.com/sibelius/ccsseraphini/issues/157#issuecomment-1050163766

**Comment by tgmarinho** [comment]
- [ ] slack integration
- [ ] discord integration

**Comment by tgmarinho** [comment]
I picked this one, integration with discord first, then we can split in another task integration with slack

**Comment by sibelius** [comment]
- [ ] discord guild id 751032355279339583
