### ISSUE TITLE
[Bug] UI - Increase the input bar

### ISSUE THREAD

**Issue by tgmarinho** [sibelius/ccsseraphini#253]
Today:

![Screen Shot 2022-03-09 at 19 15 51](https://user-images.githubusercontent.com/380327/157555223-c0070d38-1e64-4d25-9147-eac3620caf07.png)

It seems the input bar should be bigger.

Suggestion:

![Screen Shot 2022-03-09 at 19 19 16](https://user-images.githubusercontent.com/380327/157555537-e755f5fe-a33e-4096-956e-d7a5deb9ff3f.png)

**Comment by vit0rr** [comment]
Old issue and looks solved 
![image](https://user-images.githubusercontent.com/70543018/188030641-1fba6b5b-3e57-4259-b64c-bde08762e3c1.png)
