### ISSUE TITLE
earn an invite to my private discord server

### ISSUE THREAD

**Issue by sibelius** [sibelius/ccsseraphini#270]
- [x] twitter oauth (follow this https://github.com/kg0r0/twitter-oauth2-client/blob/d4815bba8e568edd1fc407be1bea10eaf2fa0344/src/index.ts#L40)
- [x] user login using twitter
- [x] we compute the score of tweets like, rt, replies (make a sum)
- [x] if the user pass a thresoald if can claim a discord invite
- [x] discord guild join https://discord.com/developers/docs/resources/guild#add-guild-member

**Comment by sibelius** [comment]
https://twitter.com/sseraphini/status/1503750926074585090

**Comment by pjonatansr** [comment]
### still needed 
- [ ]  Show discord guild claim button
- [ ]  Validate user score ([here](https://github.com/sibelius/ccsseraphini/blob/main/apps/web/src/pages/api/discord/oauth.ts))
- [ ]  Use "discordGuildJoinPut" to call  the invite
- [ ] Improve Page /Score Layout 
- [ ] Improve userScore Tweet Filter
