### ISSUE TITLE
Add max size to the tweet image preview

### ISSUE THREAD

**Issue by pjonatansr** [sibelius/ccsseraphini#277]
We need to set a max size to the tweet image preview to prevent to fill all the screen with only one tweet.
![image](https://user-images.githubusercontent.com/5343791/159139731-7c9c50f8-8f6e-4a44-a99b-e7fe29805165.png)

**Comment by noghartt** [comment]
I think that we can add a *max size* and an option to click on it to expand as a modal, similar to a tweet.

**Comment by vit0rr** [comment]
Solved https://github.com/sibelius/ccsseraphini/pull/302
