### ISSUE TITLE
Download score card image

### ISSUE THREAD

**Issue by arantespp** [sibelius/ccsseraphini#310]
# Feature Request

A great feature is the possibility to download the scorecard as a downloadable image to share on Twitter or LinkedIn (yes, it'd be amazing to start evangelizing cc @sseraphini on LinkedIn).

## Why it is needed

It's fun to share with others my points.

## Possible implementation

We can solve it by creating an `useImage` hook with this API:

```tsx title="component.tsx"
const { ref, download, isDownloading } = useImage();

return <>
    <DivIWantToDownload ref={ref} />
    <Button onClick={download} />  
  </>
```

The `useImage` hook algorithm can be something like this (I'm going to reference a feature that I created to create Instagram posts automatically):

- Create a `ref` to be the div reference. [Reference.](https://github.com/arantespp/arantespp.com/blob/ccf1641f4bf9623266b7a5ce48a2ac9df75e02e6/src/components/InstagramPost.tsx#L218)
- Create an `useEffect` that checks if the `ref` exists, and if it exists, use [html2canvas lib](https://html2canvas.hertzen.com/) to transform the div in canvas and base64 string and save in the `image` state. [Reference.](https://github.com/arantespp/arantespp.com/blob/ccf1641f4bf9623266b7a5ce48a2ac9df75e02e6/src/components/InstagramPost.tsx#L233)
- Create an `useCallback` to download the image saved on `image` state. [Reference.](https://github.com/arantespp/arantespp.com/blob/ccf1641f4bf9623266b7a5ce48a2ac9df75e02e6/src/components/InstagramPost.tsx#L257)

**Comment by sibelius** [comment]
maybe another button
