### ISSUE TITLE
Add security to flood serverless function 

### ISSUE THREAD

**Issue by tgmarinho** [sibelius/ccsseraphini#320]
To solve security you can set headers: "header-flood-secret-key": "my-super-passwd" and store inside of the .env `CRONJOB_HEADER_SECRET =  "my-super-passwd"` 

and compare with the value of `"header-flood-secret-key" === CRONJOB_HEADER_SECRET `

_Originally posted by @tgmarinho in https://github.com/sibelius/ccsseraphini/issues/319#issuecomment-1079444198_

**Comment by tgmarinho** [comment]
WIP

**Comment by sibelius** [comment]
same as https://github.com/sibelius/ccsseraphini/issues/321
