### ISSUE TITLE
[Discord] Don't allow to send duplicated tweets on #tweets channel

### ISSUE THREAD

**Issue by tgmarinho** [sibelius/ccsseraphini#321]
To fix duplicated, cron job can call every 5 minutes, but we can loss some tweets or we can store the latest tweet id sent do discord, maybe using mongoatlas or faunadb

_Originally posted by @tgmarinho in https://github.com/sibelius/ccsseraphini/issues/319#issuecomment-1079447045_

**Comment by Nick-Gabe** [comment]
maybe it isn't needed to run every 5 minutes, i think mantaining a cached list of posted tweets and use them to do a verification would be enough to prevent those duplicates

**Comment by sibelius** [comment]
we have this on #tweets  channel already using stream
