### ISSUE TITLE
Setup Sentry to catch errors and creating issues automatically

### ISSUE THREAD

**Issue by tgmarinho** [sibelius/ccsseraphini#345]
https://docs.sentry.io/platforms/javascript/guides/nextjs/

**Comment by tgmarinho** [comment]
WIP

**Comment by tgmarinho** [comment]
setup github+sentry:

- []
https://github.com/getsentry/sentry/tree/master/src/sentry_plugins/github
https://docs.github.com/pt/developers/apps/building-github-apps/creating-a-github-app

**Comment by sibelius** [comment]
sentry is there, tks
