### ISSUE TITLE
bug responsive on iOS

### ISSUE THREAD

**Issue by sibelius** [sibelius/ccsseraphini#367]
![image](https://user-images.githubusercontent.com/2005841/161343887-6d2e3ab8-67d2-41a0-98f2-8fb002d57ef1.png)

- [ ] https://sseraphini.cc/score/sseraphini

**Comment by rafasilveira** [comment]
I've also found out that the Home Screen is a bit misaligned. I'll take a look on both.
![image](https://user-images.githubusercontent.com/64478636/161344813-35b535b1-c5ad-403d-b28d-dcf41c185000.png)

**Comment by sibelius** [comment]
responsive is hard

**Comment by Nick-Gabe** [comment]
eu entrei na área pq pensei que ia só pintar botões 😭

**Comment by vit0rr** [comment]
Solved at https://github.com/sibelius/ccsseraphini/pull/372
Closing issue
