### ISSUE TITLE
OG description errada

### ISSUE THREAD

**Issue by vit0rr** [sibelius/ccsseraphini#368]
# Bug

Quando pesquisa por "cc seraphini" aparece um tweet
![image](https://user-images.githubusercontent.com/70543018/161346266-797311a4-d2ec-40e5-b0b8-c28f15cb6007.png)

**Comment by italosantana** [comment]
O que estão pensando em colocar como description da og?

**Comment by vit0rr** [comment]
> O que estão pensando em colocar como description da og?

O que é cc seraphini?

**Comment by vit0rr** [comment]
Não acho que vamos chamar gente nova do cc seraphini com uma descrição decente. Quem usa isso já sabe o que está fazendo. A descrição que já existe é o suficiente

"Make it easy to cc @sseraphini"

O problema que deu, é que provavelmente foi SEO automático quando o Sibs comprou o domínio e o DNS rodou por ai... Então imagino que se tentar manualmente algumas técnicas de SEO deve atualizar a descrição pro que foi colocado no código na meta tag

**Comment by vit0rr** [comment]
Looks solved 
![image](https://user-images.githubusercontent.com/70543018/188030230-78ebc5c0-69c0-4938-ad97-3a8e5e55ed2c.png)

Closing issue
