### ISSUE TITLE
make it closer to twitter

### ISSUE THREAD

**Issue by sibelius** [sibelius/ccsseraphini#51]
- [ ] sseraphini.cc
![image](https://user-images.githubusercontent.com/2005841/150115207-d49704a4-0b36-4b96-a64c-8fd85c652605.png)
- [ ] twitter
![image](https://user-images.githubusercontent.com/2005841/150115254-62c31a4e-26da-467a-a6bc-d7d643f3d4da.png)
- [x] retweets counts
- [x] likes count
- [x] tweet time
- [ ] be able to go to tweet user

**Comment by sibelius** [comment]
copy tweet design

**Comment by danielcti** [comment]
I dont't know why there is &gt and not >, maybe we need to decode the tweet text.
![image](https://user-images.githubusercontent.com/31549323/150192602-9dd8a570-3128-481f-b251-eb0fad3b05e7.png)
