### ISSUE TITLE
A chrome extension

### ISSUE THREAD

**Issue by noghartt** [sibelius/ccsseraphini#55]
Write an extension to chrome browser that is able to write tweets with "cc @sseraphini".

## References

- [Creating a Chrome Extension with React](https://javascript.plainenglish.io/creating-a-chrome-extension-with-react-d92db20550cb)

**Comment by sibelius** [comment]
boilerplate https://github.com/sibelius/ccsseraphini/pull/72

**Comment by sibelius** [comment]
- [ ] release CI/CD

**Comment by sibelius** [comment]
fixed here https://chrome.google.com/webstore/detail/ccsseraphini/jbdolkjfpfgpbdeeebkhnmfnbkplgalm
