### ISSUE TITLE
RT from Discord

### ISSUE THREAD

**Issue by arantespp** [sibelius/ccsseraphini#576]
# Feature Request

RT from Discord

## Why it is needed

Decentralize sseraphini and sseramemes.

## Possible implementation

We need to create a package that listens to a tweet pattern, sends it to a Discord channel, and lets the community vote if it'll be retweeted.

1. Create a server that uses Twitter Stream API to listen to a tweet pattern.
2. Send matched tweets to a Discord channel and wait for the community voting.
3. If the tweet reaches a minimum of voting points, retweet it.

### Code sample

A possible usage of the package:

```ts
import { rtFomDiscrod } from '@ccsseraphini/rt-from-discord';

rtFomDiscrod.start({
  emojisPoints: {
    💯: 1,
    👎: -3,
  },
  minPoints: 3,
  discordChannelId: 'channel to vote',
  tweetPattern: 'regex or string',
  ... // twitter and discord tokens.
});
```

**Comment by vit0rr** [comment]
Will be cool if any person can subscribe to do RT with Sibelius.

Multiples rts
