### ISSUE TITLE
first wrapper do not make clear that exist the latest tweets ui/ux

### ISSUE THREAD

**Issue by daniloab** [sibelius/ccsseraphini#68]
## Why it is needed
Make clear and usable to understand that exist the latest tweet timeline
![Screen Shot 2022-01-20 at 12 30 44](https://user-images.githubusercontent.com/19939822/150369634-0d3a3244-e97c-4f38-9437-a651405638e6.png)

## Possible implementation
- [ ] improve the CSS
- [ ] or have some icon showing that has more content to below

### Code sample
- [ ] add a bottom arrow
- [ ] or just uncenter the content from first wrapper to have something like
![Screen Shot 2022-01-20 at 12 31 32](https://user-images.githubusercontent.com/19939822/150369816-0b1c6e47-2f5d-4b0f-a4a7-44309ddb5cce.png)

**Comment by biantris** [comment]
good issue!

**Comment by sibelius** [comment]
fixed here https://github.com/sibelius/ccsseraphini/pull/76
