### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by sibelius** [sibelius/ccsseraphini#8]
dark mode would be cool

**Comment by lukelima** [comment]
We need a Sibelius logo with 🕶️ for dark mode

**Comment by sibelius** [comment]
what about just inverting the colors of my logo for now?

**Comment by ubmit** [comment]
@santosant are you working on this issue?

**Comment by sibelius** [comment]
feel free to give a try

**Comment by sibelius** [comment]
https://github.com/sibelius/ccsseraphini/pull/22

this was the first attempt

**Comment by sibelius** [comment]
good enough tks
