### ISSUE TITLE
BUG - Discord Guild Claim on /score not working

### ISSUE THREAD

**Issue by brunocroh** [sibelius/ccsseraphini#803]
# Bug

When I try to join discord at https://sseraphini.cc/score I am redirected to discord authorization, but I get a 401 error

## Steps To Reproduce

https://user-images.githubusercontent.com/13812512/177374467-8a8cd7df-10fc-4cff-b2e1-ca958fdd0ed8.mov

Describe what you expected to happen:

1. Enter a discord server

**Comment by sibelius** [comment]
thanks, fixed the discord bot token
