### ISSUE TITLE
fixed sseraphini box

### ISSUE THREAD

**Issue by EmanuelCampos** [sibelius/ccsseraphini#85]
make the sseraphini box fixed to follow the latest tweets

![image](https://user-images.githubusercontent.com/16262455/150776278-3ab34e64-a136-4327-b7ce-e63a934c9f8b.png)

![image](https://user-images.githubusercontent.com/16262455/150776212-cddfd0d1-d2ca-43f1-8ced-945d0ec45e5a.png)

**Comment by sibelius** [comment]
make it stick

**Comment by sibelius** [comment]
fixed it here https://github.com/sibelius/ccsseraphini/pull/128
